[package]
name = "cargo-fuzz"
version = "0.2.2"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Simple wrapper around libFuzzer"
repository = "https://github.com/rust-fuzz/cargo-fuzz/"

[dependencies]
cargo_metadata  = "0.1.2"
toml            = "0.3"
term            = "0.4.5"
clap            = "2.20.5"
