[package]
name = "cargo-fuzz"
version = "0.5.5"
authors = ["The rust-fuzz Project Developers"]
license = "MIT OR Apache-2.0"
description = "Simple wrapper around libFuzzer"
repository = "https://github.com/rust-fuzz/cargo-fuzz/"
categories = ["development-tools::testing"]
edition = "2018"

[dependencies]
clap            = "2.33.0"
error-chain     = "0.12.1"
tempdir         = "0.3.7"
term            = "0.6.1"
toml            = "0.5.5"

[workspace]
members = ["."]
